learning_auth/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('register', views.register, name='register'),
    path('user_login', views.user_login, name='user_login'),
]

learning_auth/learning_auth/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('logout', views.user_logout,name='logout'),
    path('special/', views.special,name='special'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_auth/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_url = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    
    def __str__(self):
        return self.user.username

learning_auth/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_url', 'profile_pic')

learning_auth/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    return render(request,'basic_app/index.html')

def register(request):

    registered=False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        user_profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid and user_profile_form.is_valid:
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = user_profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered=True

        else:
            print(user_form.errors, user_profile_form.errors)
    else:
        user_form = UserForm()
        user_profile_form = UserProfileInfoForm()
    return render(request, 'basic_app/registration.html', context=
                                {'user_form':user_form,
                                 'user_profile_form':user_profile_form,
                                 'registered':registered})

        
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not Active")
        else:
            print("Invalid user credentials: ")
            print("Username: {} and Password: {}.format(username, password)")
            return HttpResponse("Credentials not valid")
    else:
        return render(request,'basic_app/login.html',{})

@login_required
def  user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged In!")

learning_auth/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:register' %}">Registration</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>     
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'special' %}">Special</a>
                </li>                     
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>                         
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
                </li>                     
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_blocks %}

        {% endblock %}
    </div>

</body>

</html>

learning_auth/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

{% block body_blocks%}
    <div class="jumbotron">
        <h3>Django Level 5</h3>
    </div>

{% endblock %}

learning_auth/templates/basic_app/login.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}

    {% block body_blocks %}
        <div class="jumbotron">
            <h1>Please Login</h1>
            <form action="{% url 'basic_app:user_login' %}" method="post">
                {% csrf_token %}
                <label for="username">Username:</label>
                <input type="text" name="username" placeholder="Enter Username">
                <label for="password">Password:</label>
                <input type="password" name="password" placeholder="Enter Password">
                <input type="submit" value="Login">
            </form>

        </div>
    {% endblock %}

    

learning_auth/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load static %}
{% block body_blocks %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registration</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>

        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ user_profile_form.as_p }}
            <input class="btn btn-primary" type="submit" value="Register">
        </form>
    {% endif %}

</div>

{% endblock %}